behaviors:
  Volleyball:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 
      beta: 
      epsilon: 
      lambd: 
      num_epoch: 
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 500
    checkpoint_interval: 1000000
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 20000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 10000
      team_change: 200000
      initial_elo: 1200.0
env_settings:
  env_args: null
  base_port: 5005
  num_envs: 4
  num_areas: 8
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 3
